--CHUCVU
INSERT INTO CHUCVU(MACV, TENCV) VALUES ('GD', 'Giám đốc');
INSERT INTO CHUCVU(MACV, TENCV) VALUES ('PGD', 'Phó Giám Đốc');
INSERT INTO CHUCVU(MACV, TENCV) VALUES ('TK', 'Trưởng khoa');
INSERT INTO CHUCVU(MACV, TENCV) VALUES ('TT', 'Tổ trưởng');
INSERT INTO CHUCVU(MACV, TENCV) VALUES ('NV', 'Nhân viên');