CREATE TABLE BPQL (
    MABP VARCHAR(5) PRIMARY KEY,
    TENBP VARCHAR(50) NOT NULL,
    SDT VARCHAR(10) NOT NULL
);

CREATE TABLE KHUVUC (
    MAKV VARCHAR(4) PRIMARY KEY,
    TENTINH VARCHAR(50) NOT NULL,
    TENHUYEN VARCHAR(50) NOT NULL
);

CREATE TABLE CSYT (
    MACS VARCHAR(4) PRIMARY KEY,
    DIACHI VARCHAR(4),
    SDT VARCHAR(10) NOT NULL,
	MABP VARCHAR(5),
    FOREIGN KEY (DIACHI) REFERENCES KHUVUC(MAKV) ON DELETE RESTRICT,
	FOREIGN KEY (MABP) REFERENCES BPQL(MABP) ON DELETE RESTRICT
);

CREATE TABLE KHUCACHLY (
    MAKHU VARCHAR(4) PRIMARY KEY,
    MACS VARCHAR(4),
    DIACHI VARCHAR(4),
	SOLUONGBN BIGINT NOT NULL,
    FOREIGN KEY (MACS) REFERENCES CSYT(MACS) ON DELETE RESTRICT,
    FOREIGN KEY (DIACHI) REFERENCES KHUVUC(MAKV) ON DELETE RESTRICT
);

CREATE TABLE CSVC (
    MATHIETBI VARCHAR(8) PRIMARY KEY,
    TENTHIETBI VARCHAR(200) NOT NULL
);

CREATE TABLE QLCSVCYTE (
    MATHIETBI VARCHAR(8),
    MACS VARCHAR(4),
    SL INT NOT NULL,
    PRIMARY KEY (MATHIETBI, MACS),
    FOREIGN KEY (MATHIETBI) REFERENCES CSVC(MATHIETBI) ON DELETE RESTRICT,
    FOREIGN KEY (MACS) REFERENCES CSYT(MACS) ON DELETE RESTRICT
);

CREATE TABLE CHUCVU (
    MACV VARCHAR(3) PRIMARY KEY,
    TENCV VARCHAR(20) NOT NULL
);

CREATE TABLE CANBONV (
    MACB VARCHAR(6) PRIMARY KEY,
    HOTEN VARCHAR(30) NOT NULL,
    GIOITINH BOOLEAN NOT NULL,
    SDT VARCHAR(10) NOT NULL,
    DONVICT VARCHAR(4),
    NOIHD VARCHAR(4),
    MACV VARCHAR(3),
    FOREIGN KEY (DONVICT) REFERENCES CSYT(MACS) ON DELETE RESTRICT,
    FOREIGN KEY (NOIHD) REFERENCES KHUCACHLY(MAKHU) ON DELETE RESTRICT,
    FOREIGN KEY (MACV) REFERENCES CHUCVU(MACV) ON DELETE RESTRICT
);


CREATE TABLE KHOA (
    MAKHOA VARCHAR(3) PRIMARY KEY,
    TENKHOA VARCHAR(50) NOT NULL
);

CREATE TABLE BACSI (
    MABS VARCHAR(6) PRIMARY KEY,
    HOTEN VARCHAR(30) NOT NULL,
    GIOITINH BOOLEAN NOT NULL,
    SDT VARCHAR(10) NOT NULL,
    DONVICT VARCHAR(4),
    NOIHD VARCHAR(4),
    CHUYENKHOA VARCHAR(3),
    MACV VARCHAR(3),
    FOREIGN KEY (DONVICT) REFERENCES CSYT(MACS) ON DELETE RESTRICT,
    FOREIGN KEY (NOIHD) REFERENCES KHUCACHLY(MAKHU) ON DELETE RESTRICT,
    FOREIGN KEY (CHUYENKHOA) REFERENCES KHOA(MAKHOA) ON DELETE RESTRICT,
    FOREIGN KEY (MACV) REFERENCES CHUCVU(MACV) ON DELETE RESTRICT
);

CREATE TABLE BENHNHAN (
    MABN VARCHAR(6) PRIMARY KEY,
    HOTEN VARCHAR(30) NOT NULL,
    GIOITINH BOOLEAN NOT NULL,
    NGAYSINH DATE NOT NULL,
    DIACHI VARCHAR(4),
    SDT VARCHAR(10) NOT NULL,
    QUOCTICH VARCHAR(30) NOT NULL,
    TINHTRANG VARCHAR(50) NOT NULL,
	TT_GIAMHO VARCHAR(50) NOT NULL,
    MAKHU VARCHAR(4),
    TGCACHLY INT NOT NULL,
    TGBDCACHLY DATE NOT NULL,
    TGKTCACHLY DATE NOT NULL,
    FOREIGN KEY (DIACHI) REFERENCES KHUVUC(MAKV) ON DELETE RESTRICT,
    FOREIGN KEY (MAKHU) REFERENCES KHUCACHLY(MAKHU) ON DELETE RESTRICT
);


CREATE TABLE TNV (
    MATNV SERIAL PRIMARY KEY,
    HOTEN VARCHAR(30) NOT NULL,
    SDT VARCHAR(10) NOT NULL,
    NOIHD VARCHAR(4) NOT NULL,
    FOREIGN KEY (NOIHD) REFERENCES KHUCACHLY(MAKHU) ON DELETE RESTRICT
);
